"""Unified knowledge namespace; the root exports protocol-neutral contracts."""
from knowledge.contracts import (
    CandidateRetrievalTrace,
    ChunkMetadata,
    EvaluationCandidate,
    EvaluationRetrievalResult,
    IngestionReport,
    OcrPolicy,
    ParsedChunk,
    ParserHint,
    ParseRequest,
    ParseResult,
    RagDocument,
    RagHealthStatus,
    RagValidationError,
    RetrievedChunk,
    RetrievalRequest,
    RetrievalResult,
    SourceReference,
    StoredChunk,
    WarmupStatus,
)

__all__ = [
    "CandidateRetrievalTrace",
    "ChunkMetadata",
    "EvaluationCandidate",
    "EvaluationRetrievalResult",
    "IngestionReport",
    "OcrPolicy",
    "ParsedChunk",
    "ParserHint",
    "ParseRequest",
    "ParseResult",
    "RagDocument",
    "RagHealthStatus",
    "RagValidationError",
    "RetrievedChunk",
    "RetrievalRequest",
    "RetrievalResult",
    "SourceReference",
    "StoredChunk",
    "WarmupStatus",
]
